server:
  port: 8080
  host:
spring:
  datasource:
    url: jdbc:h2:mem:study;MODE=mysql;
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  h2.console:
    enabled: true
    path: /study
  logging:
  level:
    org.hibernate.SQL: debug
  sql:
    init:
      platform: h2
# MyBatis Setting
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.studentmanagement.entity
